######################################################################
# Automatically generated by qmake (3.0) Thu Feb 16 10:13:13 2023
######################################################################

QT += core gui widgets
CONFIG += c++17

TEMPLATE = app
TARGET = events
INCLUDEPATH += .

# Input
HEADERS += logger.hpp widget.hpp \
    shape.h
SOURCES += logger.cpp main.cpp widget.cpp
